<?php
/**
 * PHP Snippets Report admin page.
 *
 * Renders the latest snippet sweep report under Tools. The report is
 * generated by the sweep workflow in .github/workflows/sweep.yml, which runs
 * every interactive PHP snippet on the parsed reference pages through
 * WordPress Playground and publishes the results to the sweep-report branch.
 *
 * @package wporg-developer
 */

/**
 * Class to handle the PHP Snippets Report admin page.
 */
class DevHub_Snippets_Report {

	/**
	 * Admin page slug.
	 *
	 * @var string
	 */
	const PAGE = 'php-snippets-report';

	/**
	 * Report written by `yarn sweep:report`, relative to the WordPress root.
	 *
	 * Only a local development environment maps the repository `env` directory
	 * into the WordPress root, so the file is absent everywhere else.
	 *
	 * @var string
	 */
	const LOCAL_REPORT = 'env/sweep/results/report.json';

	/**
	 * Bucket labels, keyed by bucket and ordered for display.
	 *
	 * @var array
	 */
	public static $buckets = array(
		'ran-match'       => 'Matched expected output',
		'ran-ok'          => 'Ran without expected output',
		'ran-mismatch'    => 'Differed from expected output',
		'ran-error'       => 'Failed to run',
		'no-output'       => 'Produced no output',
		'not-runnable'    => 'Rendered without a Run action',
		'never-completed' => 'Never completed',
	);

	/**
	 * Initializer.
	 */
	public static function init() {
		add_action( 'admin_menu', array( __CLASS__, 'add_page' ) );
		add_action( 'admin_enqueue_scripts', array( __CLASS__, 'enqueue_assets' ) );
	}

	/**
	 * Registers the admin page.
	 */
	public static function add_page() {
		add_management_page(
			__( 'PHP Snippets Report', 'wporg' ),
			__( 'PHP Snippets Report', 'wporg' ),
			'edit_posts',
			self::PAGE,
			array( __CLASS__, 'render_page' )
		);
	}

	/**
	 * Enqueues the report stylesheet and script on the report page.
	 *
	 * @param string $hook_suffix The current admin page.
	 */
	public static function enqueue_assets( $hook_suffix ) {
		if ( 'tools_page_' . self::PAGE !== $hook_suffix ) {
			return;
		}

		wp_enqueue_style(
			'devhub-snippets-report',
			get_stylesheet_directory_uri() . '/stylesheets/snippets-report.css',
			array(),
			filemtime( dirname( __DIR__ ) . '/stylesheets/snippets-report.css' )
		);

		wp_enqueue_script(
			'devhub-snippets-report',
			get_stylesheet_directory_uri() . '/js/snippets-report.js',
			array(),
			filemtime( dirname( __DIR__ ) . '/js/snippets-report.js' ),
			true
		);
	}

	/**
	 * Returns the report, preferring a locally swept one.
	 *
	 * The published report is cached for an hour.
	 *
	 * @return array|null The decoded report, or null when unavailable.
	 */
	public static function get_report() {
		$local = ABSPATH . self::LOCAL_REPORT;

		if ( is_readable( $local ) ) {
			return self::decode( file_get_contents( $local ) );
		}

		$report = get_transient( 'devhub_snippets_report' );

		if ( false !== $report ) {
			return $report ?: null;
		}

		$url = apply_filters(
			'devhub_snippets_report_url',
			'https://raw.githubusercontent.com/WordPress/wporg-developer/sweep-report/report.json'
		);

		$response = wp_remote_get( $url, array( 'timeout' => 15 ) );

		$report = null;

		if ( ! is_wp_error( $response ) && 200 === wp_remote_retrieve_response_code( $response ) ) {
			$report = self::decode( wp_remote_retrieve_body( $response ) );
		}

		set_transient( 'devhub_snippets_report', $report ?: '', HOUR_IN_SECONDS );

		return $report;
	}

	/**
	 * Decodes a report body.
	 *
	 * @param string $body The report body.
	 * @return array|null The decoded report, or null when it carries no results.
	 */
	public static function decode( $body ) {
		$report = json_decode( $body, true );

		if ( ! is_array( $report ) || empty( $report['results'] ) ) {
			return null;
		}

		return $report;
	}

	/**
	 * Renders the admin page.
	 */
	public static function render_page() {
		$report = self::get_report();

		echo '<div class="wrap devhub-snippets-report">';
		echo '<h1>' . esc_html__( 'PHP Snippets Report', 'wporg' ) . '</h1>';

		if ( ! $report ) {
			echo '<p>' . esc_html__( 'No sweep report is available yet. The report is published by the snippet sweep workflow.', 'wporg' ) . '</p>';
			echo '</div>';

			return;
		}

		$results = $report['results'];
		$pages   = self::group_by_page( $results );

		echo '<p>' . esc_html(
			sprintf(
				/* translators: 1: Number of snippets, 2: Number of pages, 3: Report date. */
				__( '%1$d snippets swept across %2$d pages on %3$s.', 'wporg' ),
				count( $results ),
				count( $pages ),
				mysql2date( get_option( 'date_format' ), $report['generated'] )
			)
		) . '</p>';

		self::render_totals( $report['totals'], count( $results ) );
		self::render_pages( $pages );
		self::render_snippets( $results, $pages );

		echo '</div>';
	}

	/**
	 * Groups results by reference page.
	 *
	 * @param array $results The sweep results.
	 * @return array The per-page bucket counts, keyed by page key.
	 */
	public static function group_by_page( $results ) {
		$pages = array();

		foreach ( $results as $result ) {
			$key = self::page_key( $result );

			if ( ! isset( $pages[ $key ] ) ) {
				$pages[ $key ] = array(
					'page'   => $result['page'],
					'type'   => $result['type'],
					'total'  => 0,
					'counts' => array_fill_keys( array_keys( self::$buckets ), 0 ),
				);
			}

			$pages[ $key ]['counts'][ $result['bucket'] ]++;
			$pages[ $key ]['total']++;
		}

		return $pages;
	}

	/**
	 * Returns the key that identifies the page a result belongs to.
	 *
	 * Slugs repeat across post types, so the type is part of the key.
	 *
	 * @param array $result One sweep result.
	 * @return string The page key.
	 */
	public static function page_key( $result ) {
		return $result['type'] . '--' . $result['page'];
	}

	/**
	 * Renders the bucket totals as filter cards.
	 *
	 * @param array $totals Snippet counts keyed by bucket.
	 * @param int   $count  Total number of snippets.
	 */
	public static function render_totals( $totals, $count ) {
		echo '<h2>' . esc_html__( 'Bucket totals', 'wporg' ) . '</h2>';
		echo '<div class="snippets-report-scroll">';
		echo '<div class="snippets-report-cards">';

		echo '<button type="button" class="snippets-report-card is-selected" data-bucket="all" aria-pressed="true">';
		echo '<span class="snippets-report-card-label">' . esc_html__( 'Total', 'wporg' ) . '</span>';
		echo '<span class="snippets-report-card-count">' . esc_html( number_format_i18n( $count ) ) . '</span>';
		echo '</button>';

		foreach ( self::$buckets as $bucket => $label ) {
			$value = $totals[ $bucket ] ?? 0;

			echo '<button type="button" class="snippets-report-card is-' . esc_attr( $bucket ) . '" data-bucket="' . esc_attr( $bucket ) . '" aria-pressed="false">';
			echo '<span class="snippets-report-card-label">' . esc_html( $label ) . '</span>';
			echo '<span class="snippets-report-card-count">' . esc_html( number_format_i18n( $value ) ) . '</span>';
			echo '<span class="snippets-report-card-share">' . esc_html( self::share( $value, $count ) ) . '</span>';
			echo '</button>';
		}

		echo '</div></div>';
	}

	/**
	 * Returns a count as a share of the total.
	 *
	 * @param int $value The count.
	 * @param int $count The total.
	 * @return string The share, as a percentage.
	 */
	public static function share( $value, $count ) {
		if ( ! $count ) {
			return '0.0%';
		}

		return number_format_i18n( $value / $count * 100, 1 ) . '%';
	}

	/**
	 * Renders the per-page rollup table.
	 *
	 * @param array $pages The per-page bucket counts.
	 */
	public static function render_pages( $pages ) {
		echo '<h2>' . esc_html__( 'Per-page rollup', 'wporg' ) . '</h2>';
		echo '<div class="snippets-report-scroll">';
		echo '<table class="widefat striped"><thead><tr>';

		self::render_sortable_header( __( 'Page', 'wporg' ), 'text' );
		self::render_sortable_header( __( 'Type', 'wporg' ), 'text' );

		foreach ( self::$buckets as $label ) {
			self::render_sortable_header( $label, 'number' );
		}

		self::render_sortable_header( __( 'Total', 'wporg' ), 'number' );

		echo '</tr></thead><tbody>';

		foreach ( $pages as $key => $row ) {
			echo '<tr>';
			echo '<td><button type="button" class="button-link snippets-report-page" data-page="' . esc_attr( $key ) . '">' . esc_html( $row['page'] ) . '</button></td>';
			echo '<td>' . esc_html( str_replace( 'wp-parser-', '', $row['type'] ) ) . '</td>';

			foreach ( array_keys( self::$buckets ) as $bucket ) {
				echo '<td class="snippets-report-number">' . esc_html( $row['counts'][ $bucket ] ) . '</td>';
			}

			echo '<td class="snippets-report-number snippets-report-strong">' . esc_html( $row['total'] ) . '</td>';
			echo '</tr>';
		}

		echo '</tbody></table></div>';
	}

	/**
	 * Renders one sortable rollup column header.
	 *
	 * @param string $label The column label.
	 * @param string $sort  How the column sorts, either `text` or `number`.
	 */
	public static function render_sortable_header( $label, $sort ) {
		$class = 'number' === $sort ? 'snippets-report-sortable snippets-report-number' : 'snippets-report-sortable';

		echo '<th class="' . esc_attr( $class ) . '" data-sort="' . esc_attr( $sort ) . '">';
		echo '<span class="snippets-report-label">' . esc_html( $label ) . '</span>';
		echo '<span class="snippets-report-arrow" aria-hidden="true"></span>';
		echo '</th>';
	}

	/**
	 * Renders the filters and the table of every swept snippet.
	 *
	 * @param array $results The sweep results.
	 * @param array $pages   The per-page bucket counts.
	 */
	public static function render_snippets( $results, $pages ) {
		echo '<h2 id="snippets-report-snippets">' . esc_html__( 'All snippets', 'wporg' ) . '</h2>';

		echo '<div class="snippets-report-filters">';

		echo '<select data-filter="bucket" aria-label="' . esc_attr__( 'Filter by result', 'wporg' ) . '">';
		echo '<option value="all">' . esc_html__( 'All buckets', 'wporg' ) . '</option>';

		foreach ( self::$buckets as $bucket => $label ) {
			echo '<option value="' . esc_attr( $bucket ) . '">' . esc_html( $label ) . '</option>';
		}

		echo '</select>';

		echo '<select data-filter="page" aria-label="' . esc_attr__( 'Filter by page', 'wporg' ) . '">';
		echo '<option value="all">' . esc_html__( 'All pages', 'wporg' ) . '</option>';

		foreach ( $pages as $key => $row ) {
			echo '<option value="' . esc_attr( $key ) . '">' . esc_html( $row['page'] ) . '</option>';
		}

		echo '</select>';

		echo '<input type="search" class="snippets-report-search" data-filter="search" placeholder="' . esc_attr__( 'Search snippets&hellip;', 'wporg' ) . '" aria-label="' . esc_attr__( 'Search snippets', 'wporg' ) . '" />';

		echo '</div>';

		echo '<p class="snippets-report-count">';
		printf(
			/* translators: 1: Number of snippets shown, 2: Total number of snippets. */
			esc_html__( 'Showing %1$s of %2$s snippets.', 'wporg' ),
			'<span class="snippets-report-shown">' . esc_html( number_format_i18n( count( $results ) ) ) . '</span>',
			esc_html( number_format_i18n( count( $results ) ) )
		);
		echo '</p>';

		echo '<div class="snippets-report-scroll">';
		echo '<table class="widefat"><thead><tr>';
		echo '<th class="snippets-report-toggle"><span class="screen-reader-text">' . esc_html__( 'Details', 'wporg' ) . '</span></th>';
		echo '<th>' . esc_html__( 'Page', 'wporg' ) . '</th>';
		echo '<th class="snippets-report-number">' . esc_html__( '#', 'wporg' ) . '</th>';
		echo '<th>' . esc_html__( 'Bucket', 'wporg' ) . '</th>';
		echo '<th>' . esc_html__( 'Status', 'wporg' ) . '</th>';
		echo '</tr></thead><tbody>';

		foreach ( $results as $position => $result ) {
			self::render_snippet( $position, $result );
		}

		echo '</tbody></table></div>';
		echo '<p class="snippets-report-empty" hidden>' . esc_html__( 'No snippet matches the filters.', 'wporg' ) . '</p>';
	}

	/**
	 * Renders one snippet row and its collapsed detail row.
	 *
	 * @param int   $position The row position in the table.
	 * @param array $result   One sweep result.
	 */
	public static function render_snippet( $position, $result ) {
		$id       = 'snippets-report-detail-' . $position;
		$bucket   = $result['bucket'];
		$output   = trim( (string) ( $result['output'] ?? '' ) );
		$status   = (string) ( $result['status'] ?? '' );
		$expected = $result['expected'] ?? null;

		echo '<tr class="snippets-report-row" data-bucket="' . esc_attr( $bucket ) . '" data-page="' . esc_attr( self::page_key( $result ) ) . '" data-search="' . esc_attr( self::search_text( $result ) ) . '">';
		echo '<td class="snippets-report-toggle"><button type="button" class="button-link" aria-expanded="false" aria-controls="' . esc_attr( $id ) . '"><span class="screen-reader-text">' . esc_html__( 'Toggle the snippet details', 'wporg' ) . '</span></button></td>';
		echo '<td>' . esc_html( $result['page'] ) . '</td>';
		echo '<td class="snippets-report-number">' . esc_html( $result['index'] + 1 ) . '</td>';
		echo '<td><span class="snippets-report-pill is-' . esc_attr( $bucket ) . '">' . esc_html( self::$buckets[ $bucket ] ?? $bucket ) . '</span></td>';
		echo '<td>' . esc_html( $status ) . '</td>';
		echo '</tr>';

		echo '<tr class="snippets-report-detail" id="' . esc_attr( $id ) . '" hidden><td colspan="5">';
		echo '<p><a href="' . esc_url( $result['url'] ) . '">' . esc_html__( 'View the reference page', 'wporg' ) . '</a></p>';

		self::render_payload( 'input', __( 'Input', 'wporg' ), (string) ( $result['input'] ?? '' ), __( '(no source)', 'wporg' ) );

		if ( null !== $expected ) {
			self::render_payload( 'expected', __( 'Expected', 'wporg' ), (string) $expected, __( '(empty)', 'wporg' ) );
		}

		self::render_payload( 'output', __( 'Output', 'wporg' ), $output, __( '(no output)', 'wporg' ) );

		echo '</td></tr>';
	}

	/**
	 * Renders one labelled block of snippet text.
	 *
	 * @param string $name        The payload name, used as a modifier class.
	 * @param string $label       The block label.
	 * @param string $text        The text.
	 * @param string $placeholder Shown when the text is empty.
	 */
	public static function render_payload( $name, $label, $text, $placeholder ) {
		echo '<h3 class="snippets-report-payload-label">' . esc_html( $label ) . '</h3>';
		echo '<pre class="snippets-report-payload is-' . esc_attr( $name ) . '">' . esc_html( '' === trim( $text ) ? $placeholder : $text ) . '</pre>';
	}

	/**
	 * Returns the text the search filter matches against.
	 *
	 * @param array $result One sweep result.
	 * @return string The searchable text.
	 */
	public static function search_text( $result ) {
		$parts = array(
			$result['page'],
			$result['status'] ?? '',
			$result['input'] ?? '',
			$result['output'] ?? '',
		);

		return strtolower( preg_replace( '/\s+/', ' ', implode( ' ', $parts ) ) );
	}

} // DevHub_Snippets_Report

DevHub_Snippets_Report::init();
