name: Build and push to build branch.

on:
    push:
        branches: [trunk]

jobs:
    build:
        runs-on: ubuntu-latest
        steps:
            - name: Checkout repository
              uses: actions/checkout@8e8c483db84b4bee98b60c0593521ed34d9990e8 # v6.0.1

            - name: Install NodeJS
              uses: actions/setup-node@395ad3262231945c25e8478fd5baf05154b1d79f # v6.1.0
              with:
                  node-version-file: '.nvmrc'

            - name: Setup PHP with PECL extension
              uses: shivammathur/setup-php@44454db4f0199b8b9685a5d763dc37cbf79108e1 # v2.36.0
              with:
                php-version: '8.4'
              env:
                COMPOSER_TOKEN: ${{ secrets.GITHUB_TOKEN }}

            - name: Install SVN
              run: sudo apt-get update && sudo apt-get install -y subversion

            - name: Install all dependencies
              run: |
                  composer install || composer update wporg/*
                  yarn

            - name: Build
              run: yarn workspaces run build

            - name: Trim the repo down to just the theme
              run: |
                  rm -rf source/wp-content/themes/wporg-developer-2023/node_modules
                  rm -rf source/wp-content/themes/wporg-developer-2023/scss
                  mv source/wp-content/themes/wporg-developer-2023 $RUNNER_TEMP
                  git rm -rfq .
                  rm -rf *
                  mv $RUNNER_TEMP/wporg-developer-2023/* .

            - name: Add all the theme files
              run: |
                  git add * --force

            - name: Append build number to version
              run: |
                  current_version=$(grep -oP 'Version: \K[0-9]+\.[0-9]+\.[0-9]+' style.css)
                  new_version="${current_version}-${GITHUB_SHA::7}"
                  sed -i "s/Version: $current_version/Version: $new_version/" style.css

            - name: Commit and push
              uses: actions-js/push@5a7cbd780d82c0c937b5977586e641b2fd94acc5 # 1.5
              with:
                  github_token: ${{ secrets.GITHUB_TOKEN }}
                  branch: build
                  force: true
                  message: 'Build: ${{ github.sha }}'
