name: Static Analysis (Linting)

# This workflow is triggered on pushes to trunk, and any PRs.
on:
    push:
        branches: [trunk]
    pull_request:

jobs:
    check:
        name: Lint everything

        runs-on: ubuntu-latest

        steps:
            - name: Checkout repository
              uses: actions/checkout@8e8c483db84b4bee98b60c0593521ed34d9990e8 # v6.0.1

            - name: Install NodeJS
              uses: actions/setup-node@395ad3262231945c25e8478fd5baf05154b1d79f # v6.1.0
              with:
                  node-version-file: '.nvmrc'

            - name: Setup PHP with PECL extension
              uses: shivammathur/setup-php@44454db4f0199b8b9685a5d763dc37cbf79108e1 # v2.36.0
              with:
                php-version: '8.1'
              env:
                COMPOSER_TOKEN: ${{ secrets.GITHUB_TOKEN }}

            - name: Install SVN
              run: sudo apt-get update && sudo apt-get install -y subversion

            - name: Install dependencies & setup configs
              run: |
                  composer install || composer update wporg/*
                  yarn
                  TEXTDOMAIN=wporg composer exec update-configs
            - name: Lint CSS
              run: |
                  yarn workspace wporg-developer-2023 lint:css
            - name: Lint JS
              run: |
                  yarn workspace wporg-developer-2023 lint:js
#             - name: Lint PHP
#               run: |
#                   composer run lint source/wp-content/themes/wporg-developer-2023
